---

# typo3_project_name: muume_website_87
# typo3_dbname: db_87
# typo3_dbuser: db_87
# typo3_dbimport: muume_db.sql.gz
# typo3_vhost: muume-website-87.loc

- name: "[TYPO3]: copy project files {{ typo3_project_name }} to home dir"
  synchronize:
    src: "../workdir/{{ typo3_project_name }}"
    dest: "/home/{{ ansible_user }}/"
    rsync_path: /usr/bin/rsync

- name: "[TYPO3]: copy project files {{ typo3_project_name }}"
  command: "rsync --delay-updates -F --compress --archive /home/{{ ansible_user }}/{{ typo3_project_name }} /var/www/"
  notify: nginx fix file permissions

#- include: create-symlinks.yml

- name: "Drop db when importing {{ typo3_dbname }}"
  mysql_db:
    name: "{{ typo3_dbname }}"
    state: absent
  when: typo3_dbimport is defined

- name: "Create mysql database {{ typo3_dbname }}"
  mysql_db:
    name: "{{ typo3_dbname }}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci

- name: "Create mysql user: {{ typo3_dbuser }}"
  mysql_user:
    name: "{{ typo3_dbuser }}"
    password: "{{ typo3_dbpass }}"
    host: localhost
    state: present
    priv: "{{ typo3_dbname }}.*:ALL"

- name: Copy database dump file
  copy:
    src: "data/fixtures/{{ typo3_dbimport }}"
    dest: /tmp
  when: typo3_dbimport is defined

- name: Restore database
  mysql_db:
    name: "{{ typo3_dbname }}"
    state: import
    target: "/tmp/{{ typo3_dbimport }}"
  when: typo3_dbimport is defined

- name: Run composer install
  command: "php{{ php_ver }} /usr/bin/composer install chdir=/var/www/{{ typo3_project_name }}"
  notify: nginx fix file permissions

- name: "Create vhost for {{ typo3_vhost }}"
  template:
    src: vhost-typo3.conf
    dest: "/etc/nginx/sites-available/{{ typo3_vhost }}"

- name: "Create vhost symlink for {{ typo3_vhost }}"
  file:
    src: "/etc/nginx/sites-available/{{ typo3_vhost }}"
    dest: "/etc/nginx/sites-enabled/{{ typo3_vhost }}"
    state: link
  notify: restart nginx
